version: '3.8'

services:
  # PostgreSQL Database with pgvector
  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - rag-network

  # FastAPI Backend
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
    depends_on:
      - postgres
    volumes:
      - ./app:/app/app:ro  # Mount source for development
    networks:
      - rag-network

  # React Frontend
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
      - REACT_APP_NAME=Persona
      - REACT_APP_DEBUG=true
    depends_on:
      - backend
    networks:
      - rag-network

volumes:
  postgres_data:
    name: rag_postgres_data

networks:
  rag-network:
    name: rag-network
    driver: bridge