[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"

[[services]]
name = "backend"
source = "."

[[services]]
name = "frontend" 
source = "./frontend"